 #steps:
 ## Build the container image 
 #- name: 'gcr.io/cloud-builders/docker'
 #  args: ['build', '-t', 'gcr.io/gcp-developer-1/blazor-wasm-with-docker', '.']
 ## Push the container image to Container Registry
 #- name: 'gcr.io/cloud-builders/docker'
 #  args: ['push', 'gcr.io/gcp-developer-1/blazor-wasm-with-docker']
 ## Deploy container image to Cloud Run
 #- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
 #  entrypoint: gcloud
 #  args:
 #  - 'run'
 #  - 'deploy'
 #  - 'blazor-wasm-with-docker'
 #  - '--image'
 #  - 'gcr.io/gcp-developer-1/blazor-wasm-with-docker'
 #  - '--region'
 #  - 'us-central1'
 #images:
 #- 'gcr.io/gcp-developer-1/blazor-wasm-with-docker'
 
 steps:
 # Build the container image 
 - name: 'gcr.io/cloud-builders/docker'
   args: ['build', '-t', 'gcr.io/$PROJECT_ID/blazor-wasm-with-docker:$COMMIT_SHA', './BlazorWasmWithDocker']
 # Push the container image to Container Registry
 - name: 'gcr.io/cloud-builders/docker'
   args: ['push', 'gcr.io/$PROJECT_ID/blazor-wasm-with-docker:$COMMIT_SHA']
 # Deploy container image to Cloud Run
 - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
   entrypoint: gcloud
   args:
   - 'run'
   - 'deploy'
   - 'blazor-wasm-with-docker'
   - '--image'
   - 'gcr.io/$PROJECT_ID/blazor-wasm-with-docker: '
   - '--region'
   - 'us-central1'
 images:
 - 'gcr.io/$PROJECT_ID/blazor-wasm-with-docker:$COMMIT_SHA'